const weapons = {
    sniper: [
        'CSRX 300',
    ],
    slug: [
        'BOSG 12.2',
        'TCSG12',
    ],
    mmr: [
        'OTs - 03',
        'SR - 25',
        'CAMRS',
        '417',
        'AR - 15.50',
        'MK 14 EBR',
    ],
    lmg: [
        'M249',
        'M249 SAW',
        '6 P41',
        'T - 95 LSW',
        'LMG - E',
        'G8A1',
        'ALDA 5.56',
    ],
    ar: [
        'PARA - 308',
        '552 Com',
        'ARX200',
        '556 xi',
        'L85A2',
        'C7E',
        'M762',
        'AK - 12',
        'M4',
        'V308',
        'AK - 74 M',
        '416 - C',
        'MK17 CQB',
        'AUG A2',
        'AR33',
        'Spear .308',
        'TYPE - 89',
        'C8 - SFW',
        'F90',
        'F2',
        'R4 - C',
        'G36C',
    ],
    auto_pistol: [
        'C75 Auto',
        'BEARING 9',
        'SMG - 11',
        'SPSMG9',
        'SMG - 12',
    ],
    smg: [
        '9 mm C1',
        'UMP45',
        'Commando 9',
        'M12',
        'K1A',
        'AUG A3',
        'PDW9',
        '9 x19 VSN',
        'MP7',
        'T - 5 SMG',
        'MP5K',
        'MP5 SD',
        'MP5',
        'FMG - 9',
        'P10 RONI',
        'Mx4 Storm',
        'MPX',
        'Scorpion',
        'P90',
        'Vector',
    ],
    pistol: [
        'Luison',
        'Keratos .357',
        'LFP586',
        '.44 Mag',
        'D - 50',
        'PMM',
        'Q - 929',
        'M45',
        '1911 TACOPS',
        'P229',
        'P226',
        'USP40',
        'Mk1 9 mm',
        'SDP 9 mm',
        'P9',
        'P12',
        'GSH - 18',
        'PRB92',
        '5.7 USG',
        'P - 10 C',
        'RG15',
    ],
}

export default weapons;